summary_task:
  description: >
    Summarize the internet for information about workouts from the research: {research}
  expected_output: >
    A beautifully crafted summary about workouts from the research: {research}
  agent: summary_agent
